<script>
import InkButton from "@/views/InkButton.vue";

export default {
  components: {
    InkButton,
  },
};
</script>

<template>
  <div class="about">
    <div class="title">About</div>
    <div class="empty"></div>
    <div class="text">
      The exquisite corpse is a poem, story, or drawing generated by a group
      where each group member can only see a small piece of the whole. This
      technique was first used by surrealists around 1918 in the form of poetry.
      The original game relied on a template (i.e, "The adjective noun adverb
      verb the adjective noun"), but the game can also be played by folding down
      the paper after each turn so that a given contributer sees only the
      previous sentence.
      <br />
      <br />
      Though the game began as a diversion, the surrealists also saw it as a way
      to unlock creativity and construct as a group that which was impossible to
      form individually. Years later, surrealist Andre Breton reflected that
      <b
        >"Finally, with the Exquisite Corpse we had at our command an infallible
        way of holding the critical intellect in abeyance, and of fully
        liberating the mind's metaphorical activity."</b
      >
      Whether as a serious storytelling endeavour or a fun and chaotic way to
      relax with friends, we hope you will find this same joy of creativity and
      collaboration in Exquisite!
    </div>
    <div class="empty"></div>
    <div class="back"><InkButton /></div>
  </div>
</template>

<style>
.about .title {
  color: #484848;
  /* font-family: Desyre; */
  font-family: "CalorieRegular";
  font-size: 8em;
  width: 80%;
  margin: 0 auto;
  font-weight: 200;
  text-align: left;
  line-height: 20vh;
  filter: drop-shadow(1px 2px 1px rgb(0 0 0 / 0.3));
}
.about .text {
  color: #484848;
  /* font-family: Desyre; */
  /* font-family: "CalorieRegular"; */
  font-size: 1.2em;
  width: 80%;
  margin: 0 auto;
  font-weight: 200;
  text-align: left;
  line-height: 1.7em;
}
.about .empty {
  height: 0.5vh;
}
.about .back {
  transform: scale(0.8);
  width: 30%;
  float: right;
}
</style>
